theme = "landing-page-hugo"
baseurl = "http://biodatascience-course.sciviews.org"
languageCode = "fr"
title = "Science des Données Biologiques"
canonifyUrls = "true"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
publishDir = "../biodatascience-course.github.io"

[params]
    description = "Université de Mons"
    custom_css = ["css/local.css"]

[[params.social]]
    title = "tutoriel"
    icon = "book"
    url = "http://biodatascience-course.sciviews.org/sdd-umons"
[[params.social]]
    title = "github"
    icon = "github"
    url = "https://github.com/BioDataScience-Course"
[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:sdd@sciviews.org"
